const router = require('express').Router()
const payrollControllers = require('../../../controllers/payrollControllers')
const { authMiddleware } = require("../../../middlewares/authMiddleware")

router.post('/emp-type-add', authMiddleware, payrollControllers.emp_type_add)
router.get('/employee-type-get',authMiddleware, payrollControllers.employee_type_get)
router.get('/get-emp-type-by-id/:empTypeId', payrollControllers.get_emp_type_by_id)
router.post('/emp-type-update',authMiddleware, payrollControllers.emp_type_update)
router.post('/employee-add', authMiddleware, payrollControllers.employee_add)
router.get('/get-all-employee', authMiddleware, payrollControllers.get_all_employee)
router.get('/get-leave-employees', authMiddleware, payrollControllers.get_leave_employees)
router.get('/get-pay-employees', authMiddleware, payrollControllers.get_pay_employees)
router.get('/get-employee-name-by-id/:empId', authMiddleware, payrollControllers.get_employee_name_by_id)
router.post('/leave-create', authMiddleware, payrollControllers.leave_create)
router.post('/pay-slip-create', authMiddleware, payrollControllers.pay_slip_create)
router.get('/get-all-leave', authMiddleware, payrollControllers.get_all_leave)
router.get('/get-emp-info-by-id/:empId', authMiddleware, payrollControllers.get_emp_info_by_id)
router.get('/get-all-pay-slip', authMiddleware, payrollControllers.get_all_pay_slip)
router.delete('/pay-slip-delete/:paySlipId', payrollControllers.pay_slip_delete)
router.get('/get-employee-by-id/:empId', payrollControllers.get_employee_by_id)
router.get('/get-leave-edit-by-id/:empLeaveId', payrollControllers.get_leave_by_id)
router.get('/pay-slip-view-by-id/:paySlipId', payrollControllers.pay_slip_view_by_id)
router.get('/get-pay-slip-edit-info-by-id/:paySlipId', payrollControllers.get_pay_slip_edit_info_by_id)
router.post('/pay-slip-update', payrollControllers.pay_slip_update)
router.post('/emp-update', payrollControllers.emp_update)
router.post('/leave-update', payrollControllers.leave_update)
router.delete('/leave-delete/:leaveId', payrollControllers.leave_delete)


module.exports = router